### ISSUE TITLE
runwidth.FillRight undefined

### ISSUE THREAD

**Issue by davmaz** [schachmat/wego#64] opened 2016-02-18 23:42 UTC
Hello,
  When I install with go get github.com/schachmat/wego
I get an error:
./we.go:456: undefined: runewidth.FillRight

Am I missing something?

Thanks,
Dave

**Comment by schachmat** [comment] 2016-02-18 23:46
@davmaz this is a duplicate of #63. Just add `-u` to `go get` so it updates the runewidth lib.

**Closed by schachmat** 2016-02-18 23:46 UTC
