### ISSUE TITLE
signal: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yaoshanliang** [schachmat/wego#66] opened 2016-02-20 14:39 UTC
When I run `we.go`, sometimes it is OK, sometimes is `signal: Segmentation fault (core dumped)`.

**Comment by schachmat** [comment] 2016-02-20 15:50
Please read #6 and provide more information (`go env`, …) if this doesn't help you.

**Comment by yaoshanliang** [comment] 2016-02-21 11:21
Just `signal: Segmentation fault (core dumped).`.
 My go env:
`GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/iat/workspace/code/go/path/bin"
GORACE=""
GOROOT="/home/iat/workspace/code/go/root"
GOTOOLDIR="/home/iat/workspace/code/go/root/lib/gccgo/tool"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
`

**Comment by schachmat** [comment] 2016-02-21 15:16
I'm sorry, but you have to provide more information. Which distro do you use, how did you instal go (golang-go, gccgo-go, xgcc), why did you set your GOPATH and GOROOT the way they are set? I still think its a duplicate of #6 make sure to read the [solution](https://github.com/schachmat/wego/issues/6#issuecomment-102112894) to it.

**Comment by raacker** [comment] 2016-02-22 08:03
+1 

I'm using Linux mint 17.3 and i almost finished doing this amazing stuff.

but sometimes(mostly), encounter segmention fault. It's also same on root account.

if i run it twice or third times, it shows me weather. but never done in one time.

I'm not sure how to fix it, but I think there's response time problem with weather website.

**Comment by schachmat** [comment] 2016-03-06 21:17
I assume the issue is fixed, since you did not report back for two weeks. If you can provide more info and still have trouble, feel free to reopen again.

**Closed by schachmat** 2016-03-06 21:17 UTC
