### ISSUE TITLE
iTerm box-drawing character missalignment

### ISSUE THREAD

**Issue by kvonspiczak** [schachmat/wego#5] opened 2015-05-12 14:20 UTC
Hi,

sorry I didn't necessarily wanted to open an issue for it but my ascii art looks a bit weird. At least it does not look the way it looks in the screenshot of your installation instructions.
Does it only work with specific fonts? I can't really see the clouds its just some slashes and dots. Same with the sun.

thanks in advance
kevin

**Comment by schachmat** [comment] 2015-05-12 19:59
Heyho Kevin,

I am using the dejavu font, but it should work with any UTF8 monospace font. If this does not help you solve the problem, please link a screenshot.

--schachmat

**Comment by kvonspiczak** [comment] 2015-05-13 07:28
Hey schachmat,

I'm using iTerm and oh-my-zsh (if that makes a difference). iTerm lets me configure two fonts (Regular & Non-ASCII Font). I tried to use the DejaVu Sans Mono for Powerline and this is what it looks like:
![screen shot 2015-05-13 at 09 26 20](https://cloud.githubusercontent.com/assets/2630690/7605689/60ed5db8-f952-11e4-9850-c303a37cff1d.png)

**Comment by schachmat** [comment] 2015-05-13 09:07
I see two problems there:

1. The font does not draw box-drawing characters correctly. There is too much space between the ‘dashes’ and also 1 Pixel between each line.
2. The font may be a monospace font, but it is not rendered as such. For example the string ‘Sunny“ should be exactly as wide as 5 dashes from the line above.

Zsh and oh-my-zsh should not be an issue here.

I don't know iTerm, but I assume, it does some custom magic (‘let's add some space in between the characters, because it looks better‘) in font-drawing which basically breaks all applications using the box-drawing characters. Could you test another terminal emulator? I am using [st](http://st.suckless.org/). If you find a way to configure iTerm properly, I would appreciate it if you would let me know, so I can add it to the README.

--schachmat

**Comment by schachmat** [comment] 2015-05-13 16:17
A friend of mine checked with iTerm and iTerm2 and both seem to work fine. He could reproduce the 1 pixel between lines, but not the horizontal spacing issue. He uses nearly default configs.

**Comment by arvindravi** [comment] 2015-05-14 21:15
Just jumping in to say I've got the same issue on iTerm2 with `fish` and `oh-my-fish`.

This is what I have now:

![](http://puu.sh/hNqaM/135a204b5e.png)

**Comment by arvindravi** [comment] 2015-05-14 21:31
Hey schachmat,

Here's an update on the issue. When I do `wego London` or `wego <any other place>` it works like its supposed to. But for any place in India the issue persists.

Relevant screenshot:

![](http://puu.sh/hNrql/295922ed5d.png)

**Comment by schachmat** [comment] 2015-05-15 09:12
@arvindravi this is actually another problem I described in #21. It has nothing to do with the iTerm config, but aparently you still need to remove those spaces in between the lines. It's somewhere in the configuration, but I don't have a MAC to test it, so if you find the responsible setting, please let me know.

**Comment by LazerPanther** [comment] 2015-05-18 12:36
You should see if the issue persists with the [Input Mono](http://input.fontbureau.com/download/) font.
It works perfectly for me with iTerm2 Build 2.1.1 and zsh/oh-my-zsh.

**Comment by arvindravi** [comment] 2015-05-19 03:01
@LazerPanther Yes it still is the same. London works fine on my current setup though, try `wego delhi` or `wego chennai` to see what I mean. I believe the issue is what @schachmat pointed out before.

**Comment by LazerPanther** [comment] 2015-05-19 06:37
@arvindravi Oh god, ```wego delhi``` really does break it. Didn't read your comment closely enough.

**Comment by schachmat** [comment] 2015-05-20 17:19
SInce @LazerPanther confirmed that it is a iTerm configuration issue, I'm closing this issue. If anyone has further hints on how to configure iTerm to solve the original issue by @kvonspiczak, feel free to still post them here.

**Closed by schachmat** 2015-05-20 17:19 UTC

**Comment by kvonspiczak** [comment] 2015-05-27 08:49
Hey guys I just wanted to let you know that I finally found the source of the rendering error..
Make sure you uncheck the iTerm option "Double-Width Character" under "Text" in the "Profiles" area.
Here is a screenshot:
![screen](https://cloud.githubusercontent.com/assets/2630690/7832267/04705646-045e-11e5-9577-b1b642be5b09.png)
